export const maleProductList = [
    {
        name: "Storm coat",
        image: "/images/men/hamed-darzi-u42GjVgZgV0-unsplash.jpg",
        id: "1",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/men/blue.jpg",
        id: "2",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/men/partlygreen.jpg",
        id: "3",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/men/partlypurple.jpg",
        id: "4",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/men/orangeish.jpg",
        id: "5",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/men/yellowish.jpg",
        id: "6",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/men/partlyred.jpg",
        id: "7",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/men/partlygreen.jpg",
        id: "8",
        price: 129,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/men/bluearms.jpg",
        id: "9",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/men/greenarms.jpg",
        id: "10",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/men/purplearms.jpg",
        id: "11",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/men/orangearms.jpg",
        id: "12",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/men/yellowarms.jpg",
        id: "13",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/men/redarms.jpg",
        id: "14",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/men/turqoisearms.jpg",
        id: "15",
        price: 139,
    },    
    {
        name: "Climb coat",
        image: "/images/men/allgreen.jpg",
        id: "16",
        price: 99,
    },    
    {
        name: "Climb coat",
        image: "/images/men/allpink.jpg",
        id: "17",
        price: 99,
    },    
    {
        name: "Climb coat",
        image: "/images/men/allpurple.jpg",
        id: "18",
        price: 99,
    },    
    {
        name: "Explorer coat",
        image: "/images/men/partlyorange.jpg",
        id: "19",
        price: 49,
    },    
    {
        name: "Explorer coat",
        image: "/images/men/partlyyellow.jpg",
        id: "20",
        price: 49,
    },
];