export const femaleProductList = [
    {
        name: "Storm coat",
        image: "/images/women/hamed-darzi-u42GjVgZgV0-unsplash.jpg",
        id: "1",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/women/blue.jpg",
        id: "2",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/women/partlygreen.jpg",
        id: "3",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/women/partlypurple.jpg",
        id: "4",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/women/orangeish.jpg",
        id: "5",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/women/yellowish.jpg",
        id: "6",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/women/partlyred.jpg",
        id: "7",
        price: 129,
    },    
    {
        name: "Storm coat",
        image: "/images/women/partlygreen.jpg",
        id: "8",
        price: 129,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/women/bluearms.jpg",
        id: "9",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/women/greenarms.jpg",
        id: "10",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/women/purplearms.jpg",
        id: "11",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/women/orangearms.jpg",
        id: "12",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/women/yellowarms.jpg",
        id: "13",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/women/redarms.jpg",
        id: "14",
        price: 139,
    },    
    {
        name: "Rainyday jacket",
        image: "/images/women/turqoisearms.jpg",
        id: "15",
        price: 139,
    },    
    {
        name: "Climb coat",
        image: "/images/women/allgreen.jpg",
        id: "16",
        price: 99,
    },    
    {
        name: "Climb coat",
        image: "/images/women/allpink.jpg",
        id: "17",
        price: 99,
    },    
    {
        name: "Climb coat",
        image: "/images/women/allpurple.jpg",
        id: "18",
        price: 99,
    },    
    {
        name: "Explorer coat",
        image: "/images/women/partlyorange.jpg",
        id: "19",
        price: 49,
    },    
    {
        name: "Explorer coat",
        image: "/images/women/partlyyellow.jpg",
        id: "20",
        price: 49,
    },
];